spring:
  datasource:
    url: jdbc:mysql:///exam
    username: root
    password: 198361
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.example.exam.entity

logging:
  level:
    com.example.exam.dao: trace
    org.springframework.jdbc: trace
file:
  upload: D:\up